<div class="bs-example">
<h2 class="text-center">How do glucometers work?</h2>
<blockquote>
    <h3 class="text-center">Through a pinprick several times a day — but what if diabetics could tell their blood-sugar levels anytime, by glancing at a tattoo?…</h3>
    <p class="text-center">Monitoring blood sugar levels is a pain for the diabetic — both figuratively and literally. Several times a day, they prick a finger to obtain a blood droplet and apply it to a plastic strip that’s inserted in a glucometer — a hand-held device that tells them if their glucose level is high, low, or right on target.</p>
    <br><p class="text-center">It’s usually the job of the pancreas to keep track of sugar levels and to secrete glucagon and insulin to keep them at 100 or so milligrams per deciliter of blood. But for diabetics — either because their pancreas doesn’t function properly or because their body can’t process the hormones it secretes — glucose testing is a do-it-yourself proposition. And a crucial one. Blood-sugar checks show if it’s time to inject a few units of insulin — or grab a lifesaving snack.</p>
    <br><p class="text-center">That’s where the glucometer comes in. “Current glucometers use test strips containing glucose oxidase, an enzyme that reacts to glucose in the blood droplet, and an interface to an electrode inside the meter,” explains Michael Strano, the Charles and Hilda Roddey Associate Professor of Chemical Engineering at MIT. “When the strip is inserted into the meter, the flux of the glucose reaction generates an electrical signal,” he says. “The glucometer is calibrated so the number appearing in its digital readout corresponds to the strength of the electrical current: The more glucose in the sample, the higher the number.”</p>
    <br><p class="text-center">Periodic tests via glucometer play an important part in the diabetic’s treatment plan, but current models fall short in giving a true picture of glucose fluctuations in real time. “The complications of diabetes stem from the blood sugar going outside the safe range,” says Strano. Catching those times and intervening appropriately can, in theory, lessen the negative effects of the disease, which can include heart disease, blindness, limb amputation, and kidney failure.</p>
    <br><p class="text-center">Strano and his team, with funding from MIT’s Deshpande Center for Technological Innovation, are creating the next generation of glucose testing. Their system consists of an ink made of glucose-responsive carbon nanotubes. The ink would be injected under the skin in a design a few centimeters square, creating a sugar-sensitive tattoo. “When near-infrared light is shone on the ink, it would change color in response to the blood glucose level,” he says — a welcome change for the millions of diabetics weary of frequent finger pricks. “The user would have continuous real-time glucose information and wouldn’t have to query at all.”</p>
    <br><p class="text-center">And could creative diabetics design their own custom nanotube image?  “You could possibly do that,” says Strano. “I’ve actually been contacted by several tattoo artists who are interested in working with us.”</p>
    <br><p class="text-center">Animal testing of Strano’s nanotube model is ongoing, and human trials are expected to begin within a year.</p>
</blockquote>
</div>